scan_filter_chain:
  - name: angle
    #type: laser_filters/LaserScanAngularBoundsFilterInPlace
    type: laser_filters/LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.571
      upper_angle: 1.571
